### ISSUE TITLE
Unable to compile on Windows

### ISSUE THREAD

**Issue by Darthagnon** [MultiMC/MultiMC5#3156]
System Information
-----------------------------
MultiMC version:
Latest development source, cloned from GitHub
Operating System:
Windows 10 v1709 amd64

Summary of the issue or suggestion:
----------------------------------------------
I'm trying to follow the build instructions for Windows from [here](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md) to build MultiMC5 from source (the [old build instructions for MultiMC4](https://github.com/Forkk/MultiMC4/wiki/Compiling-MultiMC) I assume are outdated). 

I have installed the following dependencies:

Qt (Log from the Qt Maintenance Tool)
- Qt v5.14.2
  - MinGW 7.3.0 64-bit
  - MinGW 7.3.0 32-bit
- Developer and Designer Tools
  - Qt Creator 4.12.0
  - Debugging Tools for Windows
  - MinGW 7.3.0 32-bit
  - MinGW 7.3.0 64-bit
  - CMake 3.16.0 32-bit
  - CMake 3.16.0 64-bit
  - Ninja 1.9.0
  - OpenSSL 1.1.1d Toolkit

Other dependencies (outside Qt)
- [ZLib 1.2.3](http://gnuwin32.sourceforge.net/downlinks/zlib.php)
- [Win32 OpenSSL Light 1.1.1g](http://slproweb.com/download/Win32OpenSSL_Light-1_1_1g.exe)
- [JDK v8u251 x64](https://www.oracle.com/java/technologies/javase-jdk8-downloads.html)
- [CMake 3.17.2 Win32](https://cmake.org/download/)

However, builds with Qt Creator fail with "unable to find compiler" or 
```
'gmtime_r' was not declared in this scope
     struct tm *s = gmtime_r(&t, &sbuf);
                    ^~~~~~~~
```
or other miscellaneous errors. 

Builds with ```qt 5.14.2 (MinGW 7.3.0 32-bit)``` fail, unable to find a compiler.

Builds with ```qt 5.14.2 (MinGW 7.3.0 64-bit)``` fail with quazip errors ([here's a pastebin](https://pastebin.com/TRq0k7Eb)). It seems to be [the same issue this person had years ago](https://stackoverflow.com/questions/36126333/mingw-cmake-undefined-reference-to-zlib)

I read in #1641 that apparently Qt v5.4.1 was a hard requirement previously, and am wondering if Qt v5.6 (recommended by BUILD.md as the minimum version, but completely unavailable via Qt online installer and archives) might be another hard requirement of Qt?

What should happen:
------------------------------

It must be possible to build MultiMC5 for Windows successfully, as the TeamCities CI is doing so successfully. I would like to learn how to build it for myself, or narrow down potential issues and improve BUILD.md

**Comment by peterix** [comment]
I ... don't see the need of supporting development on Windows.

**Comment by Darthagnon** [comment]
No problem :) Thank you for responding.

As Murphy's Law would have it, it somehow magically built itself in Qt Creator after I added a snippet of code to ```zip.cpp```. (from here: https://github.com/mayah/tinytoml/issues/25)

I'm going back over the workflow to figure out what I changed, and will share my process here once done (and close the issue)

**Comment by peterix** [comment]
The reality is that MultiMC is and will, for the foreseeable future, be build with a different compiler, Qt 5.6, and completely different builds of all those libraries.

**Comment by Darthagnon** [comment]
> The reality is that MultiMC is and will, for the foreseeable future, be built with a different compiler, Qt 5.6, and completely different builds of all those libraries.

Aha! that's probably where I was going wrong! Couldn't find Qt v5.6 anywhere to download. I didn't intentionally use wrong versions of the libraries, just available ones that I could find. Is there a list somewhere of the specific versions required to build MultiMC5? BUILD.md implied it was non-version-specific with its library requirements.

**Comment by Darthagnon** [comment]
I managed to get it built and working perfectly with Qt 5.14.2 on Windows (tested on multiple computers). Here's my process (rough draft document):
[Readme how to build2.txt](https://github.com/MultiMC/MultiMC5/files/4659283/Readme.how.to.build2.txt)

**Comment by peterix** [comment]
Probably? I have no intention of using 5.14 any time soon, but work like this should not go to waste.

**Comment by graytoowolf** [comment]
Qt5.9 can compile the latest source code without the library. It can be compiled directly. Compiled by qt5.14, which cannot be used by other computers. It is 30MB larger than the source code compiled by 5.9

**Comment by Arxk** [comment]
You can't download Qt 5.6 for Windows using the Qt online installer anymore. If someone's struggling to find it, you can use this mirror of the offline installer: http://linorg.usp.br/Qt/archive/qt/5.6/
