### ISSUE TITLE
GCC 11.1.0 compilation errors with tag 0.6.12

### ISSUE THREAD

**Issue by Valmar33** [MultiMC/MultiMC5#3793]
### Operating System

Linux

### Description of bug

Distribution is Arch Linux. Attempting to build with 11.1.0, which has recently hit [core].

```
FAILED: libraries/systeminfo/CMakeFiles/systeminfo.dir/src/sys_unix.cpp.o 
/run/media/valmar/IronWolfRAID1/Packages/AUR/Tk-Glitch/mostlyportable-gcc/gcc-mostlyportable-current/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -Ilibraries/systeminfo -I/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo -Ilibraries/systeminfo/systeminfo_autogen/include -I/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/include -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -Wall -pedantic -Werror -Wno-deprecated-declarations -D_GLIBCXX_USE_CXX11_ABI=0 -fstack-protector-strong --param=ssp-buffer-size=4 -O3 -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -ftree-vectorize -ftree-slp-vectorize -fdiagnostics-color=always -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fPIC -fPIC -std=gnu++11 -MD -MT libraries/systeminfo/CMakeFiles/systeminfo.dir/src/sys_unix.cpp.o -MF libraries/systeminfo/CMakeFiles/systeminfo.dir/src/sys_unix.cpp.o.d -o libraries/systeminfo/CMakeFiles/systeminfo.dir/src/sys_unix.cpp.o -c /tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp
/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp: In function ‘uint64_t Sys::getSystemRam()’:
/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp:37:26: error: ‘numeric_limits’ is not a member of ‘std’
   37 |         file.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
      |                          ^~~~~~~~~~~~~~
/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp:37:56: error: expected primary-expression before ‘>’ token
   37 |         file.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
      |                                                        ^
/tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp:37:59: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   37 |         file.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
      |                                                           ^~~
      |                                                           std::max
In file included from /run/media/valmar/IronWolfRAID1/Packages/AUR/Tk-Glitch/mostlyportable-gcc/gcc-mostlyportable-11.1.1-releases-gcc.11.1.0.r126.gca205a821cd/include/c++/11/algorithm:62,
                 from /usr/include/qt/QtCore/qglobal.h:142,
                 from /usr/include/qt/QtCore/qchar.h:43,
                 from /usr/include/qt/QtCore/qstring.h:49,
                 from /usr/include/qt/QtCore/QString:1,
                 from /tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/include/sys.h:2,
                 from /tmp/makepkg/multimc5/src/MultiMC5-0.6.12/libraries/systeminfo/src/sys_unix.cpp:1:
/run/media/valmar/IronWolfRAID1/Packages/AUR/Tk-Glitch/mostlyportable-gcc/gcc-mostlyportable-11.1.1-releases-gcc.11.1.0.r126.gca205a821cd/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
```

### Steps to reproduce

1. Install Arch
2. Update to latest stable packages.
3. Build MultiMC5 with https://aur.archlinux.org/packages/multimc5/
4. Get compilation failures

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ImperatorStorm** [comment]
`multimc5` is a _very_ buggy and jank package

Bug should be fixed in devel, as of https://github.com/MultiMC/MultiMC5/commit/b8cd13bb217c0fa556d55d0c4c0d8332c556036a

**Comment by spannerman79** [comment]
> 3\. Build MultiMC5 with [aur.archlinux.org/packages/multimc5](https://aur.archlinux.org/packages/multimc5/)

I would **highly** recommend using https://aur.archlinux.org/packages/multimc-git/ instead.  Yes it is built direct from source and not at a set commit head, but I have not had any issues building nor using `multimc-git`.

**Comment by Valmar33** [comment]
Cheers. :)
